# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dcac436b9155f3092e01d35c4a38afdc"
name = "complementry product"
handle = "complementry-product"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "shiv-dev-checkout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
